name: 'me4n-macbook'

on:
 schedule:
#    - cron: '0 9 * * *'
    - cron: '30 23 * * 0-4'
#    - cron: '*/30 * * * *'
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install beautifulsoup4
        pip install pytz
        pip install PyGithub
        pip install python-dateutil
        pip install requests
        pip install python-telegram-bot
    - name: Run Crawler
      run: |
        python findCheapMacbook.py
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }} 
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }} 
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }} 
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}